language: php

php:
  - hhvm

before_script:
  - export CMAKE_PREFIX_PATH=`pwd`/..
  - cd $HPHP_HOME && git submodule update --init --recursive && time TRAVIS=1 ./configure_generic.sh
  - cd hphp/system && make -j 6 && sudo make install && cd -
  - cd ..

install:
  - sudo apt-get install cmake
  - git clone git://github.com/facebook/hhvm.git
  - export HPHP_HOME=`pwd`/hhvm

script:
  - sh $HPHP_HOME/hphp/tools/hphpize/hphpize && cmake . && make

notifications:
  email:
    - sherlockfei@gmail.com
