language: php

php:
  - hhvm

before_script:

install:
    - /home/travis/.phpenv/versions/hhvm/bin/composer self-update

script:
  - whereis hphpize
  - /usr/local/bin/hphpize && cmake . && make

notifications:
  email:
    - sherlockfei@gmail.com
