language: php

php:
  - hhvm

before_script:
  - cd $HPHP_HOME && git submodule update --init --recursive && export CMAKE_PREFIX_PATH=`pwd`/.. && time TRAVIS=1 ./configure_generic.sh
  #- cd hphp/system && make -j8 && cd -
  - cmake . && make
  - cd ..

install:
  - sudo apt-get install cmake
  - git clone git://github.com/facebook/hhvm.git
  #- cd hhvm && git checkout 1da451b && cd -  # Tag:3.0.1
  - export HPHP_HOME=`pwd`/hhvm

script:
  - sh $HPHP_HOME/hphp/tools/hphpize/hphpize && cmake . && make

notifications:
  email:
    - sherlockfei@gmail.com
