language: php

php:
  - hhvm

before_script:

install:
  - /bin/bash ./tools/travis.sh

script:
  - sh $HPHP_HOME/hphp/tools/hphpize/hphpize && cmake . && make

notifications:
  email:
    - sherlockfei@gmail.com
