language: php

php:
  - hhvm

before_script:
  - cd $HPHP_HOME && git submodule update --init --recursive && export CMAKE_PREFIX_PATH=`pwd`/.. && time TRAVIS=1 ./configure_generic.sh
  - cd hphp/system && make -j 6 && cd -
  - cd ..
  - find . -name hphpize

install:
  - sudo apt-get install cmake
  - git clone git://github.com/facebook/hhvm.git
  - export HPHP_HOME=`pwd`/hhvm

script:
  - cp "$HPHP_HOME/hphp/tools/hphpize/hphpize.cmake" CMakeLists.txt
  - cmake .
  - make

notifications:
  email:
    - sherlockfei@gmail.com
