language: php

php:
  - hhvm

before_script:

install:
    - sudo: required
    - /home/travis/.phpenv/versions/hhvm/bin/composer self-update
    - /bin/bash ./tools/travis.sh

script:
  - whereis hhvm
  - /usr/local/bin/hphpize && cmake . && make

notifications:
  email:
    - sherlockfei@gmail.com
